//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinoSunIDE.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SinoSunIDE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _00_00_ {
            get {
                object obj = ResourceManager.GetObject("(00,00)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_01_ {
            get {
                object obj = ResourceManager.GetObject("(00,01)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_02_ {
            get {
                object obj = ResourceManager.GetObject("(00,02)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_04_ {
            get {
                object obj = ResourceManager.GetObject("(00,04)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_06_ {
            get {
                object obj = ResourceManager.GetObject("(00,06)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_07_ {
            get {
                object obj = ResourceManager.GetObject("(00,07)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_08_ {
            get {
                object obj = ResourceManager.GetObject("(00,08)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_12_ {
            get {
                object obj = ResourceManager.GetObject("(00,12)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_13_ {
            get {
                object obj = ResourceManager.GetObject("(00,13)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_14_ {
            get {
                object obj = ResourceManager.GetObject("(00,14)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_18_ {
            get {
                object obj = ResourceManager.GetObject("(00,18)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_19_ {
            get {
                object obj = ResourceManager.GetObject("(00,19)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_20_ {
            get {
                object obj = ResourceManager.GetObject("(00,20)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_24_ {
            get {
                object obj = ResourceManager.GetObject("(00,24)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_25_ {
            get {
                object obj = ResourceManager.GetObject("(00,25)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_26_ {
            get {
                object obj = ResourceManager.GetObject("(00,26)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_30_ {
            get {
                object obj = ResourceManager.GetObject("(00,30)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_31_ {
            get {
                object obj = ResourceManager.GetObject("(00,31)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_32_ {
            get {
                object obj = ResourceManager.GetObject("(00,32)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_36_ {
            get {
                object obj = ResourceManager.GetObject("(00,36)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_37_ {
            get {
                object obj = ResourceManager.GetObject("(00,37)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_38_ {
            get {
                object obj = ResourceManager.GetObject("(00,38)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_39_ {
            get {
                object obj = ResourceManager.GetObject("(00,39)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_41_ {
            get {
                object obj = ResourceManager.GetObject("(00,41)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_42_ {
            get {
                object obj = ResourceManager.GetObject("(00,42)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_43_ {
            get {
                object obj = ResourceManager.GetObject("(00,43)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_44_ {
            get {
                object obj = ResourceManager.GetObject("(00,44)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_48_ {
            get {
                object obj = ResourceManager.GetObject("(00,48)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _00_49_ {
            get {
                object obj = ResourceManager.GetObject("(00,49)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01_00_ {
            get {
                object obj = ResourceManager.GetObject("(01,00)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01_12_ {
            get {
                object obj = ResourceManager.GetObject("(01,12)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01_34_ {
            get {
                object obj = ResourceManager.GetObject("(01,34)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _01_39_ {
            get {
                object obj = ResourceManager.GetObject("(01,39)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _02_00_ {
            get {
                object obj = ResourceManager.GetObject("(02,00)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _02_12_ {
            get {
                object obj = ResourceManager.GetObject("(02,12)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _02_29_ {
            get {
                object obj = ResourceManager.GetObject("(02,29)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _10_01_ {
            get {
                object obj = ResourceManager.GetObject("(10,01)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _11_01_ {
            get {
                object obj = ResourceManager.GetObject("(11,01)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _12_43_ {
            get {
                object obj = ResourceManager.GetObject("(12,43)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _16_00_ {
            get {
                object obj = ResourceManager.GetObject("(16,00)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _17_00_ {
            get {
                object obj = ResourceManager.GetObject("(17,00)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _18_00_ {
            get {
                object obj = ResourceManager.GetObject("(18,00)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _18_37_ {
            get {
                object obj = ResourceManager.GetObject("(18,37)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _24_38_ {
            get {
                object obj = ResourceManager.GetObject("(24,38)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _25_38_ {
            get {
                object obj = ResourceManager.GetObject("(25,38)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _26_38_ {
            get {
                object obj = ResourceManager.GetObject("(26,38)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _27_38_ {
            get {
                object obj = ResourceManager.GetObject("(27,38)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _42_28_ {
            get {
                object obj = ResourceManager.GetObject("(42,28)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b_uv4_project_window_1_ {
            get {
                object obj = ResourceManager.GetObject("b_uv4_project_window[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap build_target_1_ {
            get {
                object obj = ResourceManager.GetObject("build_target[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap comment_1_ {
            get {
                object obj = ResourceManager.GetObject("comment[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copy_1_ {
            get {
                object obj = ResourceManager.GetObject("copy[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cut_1_ {
            get {
                object obj = ResourceManager.GetObject("cut[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap debug_1_ {
            get {
                object obj = ResourceManager.GetObject("debug[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disable_all_bpnt_1_ {
            get {
                object obj = ResourceManager.GetObject("disable_all_bpnt[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disassembly_window_1_ {
            get {
                object obj = ResourceManager.GetObject("disassembly_window[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap enable_bpnt_1_ {
            get {
                object obj = ResourceManager.GetObject("enable_bpnt[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap find_1_ {
            get {
                object obj = ResourceManager.GetObject("find[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap findinfiles_1_ {
            get {
                object obj = ResourceManager.GetObject("findinfiles[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap functions_window_1_ {
            get {
                object obj = ResourceManager.GetObject("functions_window[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap h {
            get {
                object obj = ResourceManager.GetObject("h", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap help_1_ {
            get {
                object obj = ResourceManager.GetObject("help[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap incfind_1_ {
            get {
                object obj = ResourceManager.GetObject("incfind[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap indent_1_ {
            get {
                object obj = ResourceManager.GetObject("indent[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap insert_bpnt_1_ {
            get {
                object obj = ResourceManager.GetObject("insert_bpnt[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap kill_all_bpnt_1_ {
            get {
                object obj = ResourceManager.GetObject("kill_all_bpnt[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lowerToUpper {
            get {
                object obj = ResourceManager.GetObject("lowerToUpper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap memory_window_1_ {
            get {
                object obj = ResourceManager.GetObject("memory_window[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap output_window_1_ {
            get {
                object obj = ResourceManager.GetObject("output_window[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paste_1_ {
            get {
                object obj = ResourceManager.GetObject("paste[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rebuild_all_1_ {
            get {
                object obj = ResourceManager.GetObject("rebuild_all[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap register_window_1_ {
            get {
                object obj = ResourceManager.GetObject("register_window[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reset_1_ {
            get {
                object obj = ResourceManager.GetObject("reset[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap run_1_ {
            get {
                object obj = ResourceManager.GetObject("run[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap runtocursor_1_ {
            get {
                object obj = ResourceManager.GetObject("runtocursor[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stepinto_1_ {
            get {
                object obj = ResourceManager.GetObject("stepinto[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stepout_1_ {
            get {
                object obj = ResourceManager.GetObject("stepout[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stepover_1_ {
            get {
                object obj = ResourceManager.GetObject("stepover[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stop_1_ {
            get {
                object obj = ResourceManager.GetObject("stop[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stop_build_1_ {
            get {
                object obj = ResourceManager.GetObject("stop_build[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap target_options_1_ {
            get {
                object obj = ResourceManager.GetObject("target_options[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbox_window_1_ {
            get {
                object obj = ResourceManager.GetObject("toolbox_window[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap translate_file_1_ {
            get {
                object obj = ResourceManager.GetObject("translate_file[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap uncomment_1_ {
            get {
                object obj = ResourceManager.GetObject("uncomment[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unindent_1_ {
            get {
                object obj = ResourceManager.GetObject("unindent[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap upperTolower {
            get {
                object obj = ResourceManager.GetObject("upperTolower", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap upperTolower1 {
            get {
                object obj = ResourceManager.GetObject("upperTolower1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap watch_window_1_ {
            get {
                object obj = ResourceManager.GetObject("watch_window[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
